name: PHP Linting (Pint)

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/npm_and_yarn/*'

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Laravel Pint
          uses: aglipanci/laravel-pint-action@0.1.0
          with:
            preset: psr12

        - name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: PHP Linting (Pint)
            skip_fetch: true